
title: Cypher-Vortex
author: Jonatas
name: Cypher-Vortex
email: chyphervortex@gmail.com
description: >-
  Blog criado com o intuito de divulgar nosso trabalho e expor atualizações e informações a respeito da competição e do andamento da criação do nosso robo seguidor de linhas.   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cypher-vortex.github.io/cypherblog/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

theme: minima

# social
author: Jonatas S.
# image: /thumbnail-jumbo.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima date format.

date_format: "%b %-d, %Y"