title: Cypher-Vortex
email: chyphervortex@gmail.com
description: >-
  A following line robot   
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cypher-vortex.github.io/cypherblog/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

theme: minima

# social
author: Jonatas S.
# image: /thumbnail-jumbo.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima date format.

date_format: "%b %-d, %Y"

- { platform: github,         user_url: "https://github.com/Cypher-Vortex" }
- { platform: youtube,        user_url: "https://www.youtube.com/@CypherVortexInnovators." }
